image: Ubuntu1804  # образ для сборки

stack: node 16  # окружение

branches:
  only:
    - main  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint  # скрипт тестирования

deploy_script: # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name xoneru
  - git config --global user.email xonezzer@gmail.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
 deploy:
  release: myproduct-v$(APPVEYOR_BUILD_VERSION)
  description: 'Release description'
  provider: GitHub
  auth_token: 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